package connectors

import "strings"

// fipsCountry maps lowercased country names, common aliases, and ISO 3166-1
// alpha-2 codes to FIPS 10-4 country codes.
//
// The VALUES are FIPS 10-4, not ISO, because GDELT is FIPS-coded throughout:
// the DOC 2.0 API's sourcecountry: operator takes the FIPS 10-4 code, and the
// two systems disagree for many major countries (Germany is FIPS GM vs ISO
// DE, Japan JA vs JP, Sweden SW vs SE, Spain SP vs ES, United Kingdom UK vs
// GB). Worse, some codes swap meaning between the systems (GM is Germany in
// FIPS but Gambia in ISO, CH is China in FIPS but Switzerland in ISO), so
// two-letter INPUTS are always read as ISO alpha-2 and never as FIPS; each
// country's ISO code is an explicit key grouped with its names.
//
// Construction: the country names and aliases from the earlier ISO table,
// re-valued against the well-documented FIPS 10-4 country list, keyed
// lowercased. Entries with no single certain FIPS code that GDELT accepts
// are omitted rather than guessed (Aland Islands, Bonaire, Curacao, Sint
// Maarten, Palestine, the U.S. Minor Outlying Islands, the combined Svalbard
// and Jan Mayen); a miss falls back to quoted-phrase matching, which is
// safe. Values are the uppercase FIPS codes handed to GDELT's sourcecountry:
// operator; see location.go for when that happens.
var fipsCountry = map[string]string{
	"afghanistan":                       "AF",
	"af":                                "AF",
	"albania":                           "AL",
	"al":                                "AL",
	"algeria":                           "AG",
	"dz":                                "AG",
	"american samoa":                    "AQ",
	"as":                                "AQ",
	"andorra":                           "AN",
	"ad":                                "AN",
	"angola":                            "AO",
	"ao":                                "AO",
	"anguilla":                          "AV",
	"ai":                                "AV",
	"antarctica":                        "AY",
	"aq":                                "AY",
	"antigua and barbuda":               "AC",
	"ag":                                "AC",
	"argentina":                         "AR",
	"ar":                                "AR",
	"armenia":                           "AM",
	"am":                                "AM",
	"aruba":                             "AA",
	"aw":                                "AA",
	"australia":                         "AS",
	"au":                                "AS",
	"austria":                           "AU",
	"at":                                "AU",
	"azerbaijan":                        "AJ",
	"az":                                "AJ",
	"bahamas":                           "BF",
	"bs":                                "BF",
	"bahrain":                           "BA",
	"bh":                                "BA",
	"bangladesh":                        "BG",
	"bd":                                "BG",
	"barbados":                          "BB",
	"bb":                                "BB",
	"belarus":                           "BO",
	"by":                                "BO",
	"belgium":                           "BE",
	"be":                                "BE",
	"belize":                            "BH",
	"bz":                                "BH",
	"benin":                             "BN",
	"bj":                                "BN",
	"bermuda":                           "BD",
	"bm":                                "BD",
	"bhutan":                            "BT",
	"bt":                                "BT",
	"bolivia (plurinational state of)":  "BL",
	"bolivia":                           "BL",
	"bo":                                "BL",
	"bosnia and herzegovina":            "BK",
	"ba":                                "BK",
	"botswana":                          "BC",
	"bw":                                "BC",
	"bouvet island":                     "BV",
	"bv":                                "BV",
	"brazil":                            "BR",
	"br":                                "BR",
	"british indian ocean territory":    "IO",
	"io":                                "IO",
	"brunei darussalam":                 "BX",
	"brunei":                            "BX",
	"bn":                                "BX",
	"bulgaria":                          "BU",
	"bg":                                "BU",
	"burkina faso":                      "UV",
	"bf":                                "UV",
	"burundi":                           "BY",
	"bi":                                "BY",
	"cabo verde":                        "CV",
	"cape verde":                        "CV",
	"cv":                                "CV",
	"cambodia":                          "CB",
	"kh":                                "CB",
	"cameroon":                          "CM",
	"cm":                                "CM",
	"canada":                            "CA",
	"ca":                                "CA",
	"cayman islands":                    "CJ",
	"ky":                                "CJ",
	"central african republic":          "CT",
	"cf":                                "CT",
	"chad":                              "CD",
	"td":                                "CD",
	"chile":                             "CI",
	"cl":                                "CI",
	"china":                             "CH",
	"cn":                                "CH",
	"christmas island":                  "KT",
	"cx":                                "KT",
	"cocos (keeling) islands":           "CK",
	"cocos islands":                     "CK",
	"cc":                                "CK",
	"colombia":                          "CO",
	"co":                                "CO",
	"comoros":                           "CN",
	"km":                                "CN",
	"congo":                             "CF",
	"republic of the congo":             "CF",
	"cg":                                "CF",
	"congo, democratic republic of the": "CG",
	"democratic republic of the congo":  "CG",
	"dr congo":                          "CG",
	"cd":                                "CG",
	"cook islands":                      "CW",
	"ck":                                "CW",
	"costa rica":                        "CS",
	"cr":                                "CS",
	"côte d'ivoire":                     "IV",
	"cote d'ivoire":                     "IV",
	"ivory coast":                       "IV",
	"ci":                                "IV",
	"croatia":                           "HR",
	"hr":                                "HR",
	"cuba":                              "CU",
	"cu":                                "CU",
	"cyprus":                            "CY",
	"cy":                                "CY",
	"czechia":                           "EZ",
	"czech republic":                    "EZ",
	"cz":                                "EZ",
	"denmark":                           "DA",
	"dk":                                "DA",
	"djibouti":                          "DJ",
	"dj":                                "DJ",
	"dominica":                          "DO",
	"dm":                                "DO",
	"dominican republic":                "DR",
	"do":                                "DR",
	"ecuador":                           "EC",
	"ec":                                "EC",
	"egypt":                             "EG",
	"eg":                                "EG",
	"el salvador":                       "ES",
	"sv":                                "ES",
	"equatorial guinea":                 "EK",
	"gq":                                "EK",
	"eritrea":                           "ER",
	"er":                                "ER",
	"estonia":                           "EN",
	"ee":                                "EN",
	"eswatini":                          "WZ",
	"swaziland":                         "WZ",
	"sz":                                "WZ",
	"ethiopia":                          "ET",
	"et":                                "ET",
	"falkland islands (malvinas)":       "FK",
	"falkland islands":                  "FK",
	"fk":                                "FK",
	"faroe islands":                     "FO",
	"fo":                                "FO",
	"fiji":                              "FJ",
	"fj":                                "FJ",
	"finland":                           "FI",
	"fi":                                "FI",
	"france":                            "FR",
	"fr":                                "FR",
	"french guiana":                     "FG",
	"gf":                                "FG",
	"french polynesia":                  "FP",
	"pf":                                "FP",
	"french southern territories":       "FS",
	"tf":                                "FS",
	"gabon":                             "GB",
	"ga":                                "GB",
	"gambia":                            "GA",
	"gm":                                "GA",
	"georgia":                           "GG",
	"ge":                                "GG",
	"germany":                           "GM",
	"de":                                "GM",
	"ghana":                             "GH",
	"gh":                                "GH",
	"gibraltar":                         "GI",
	"gi":                                "GI",
	"greece":                            "GR",
	"gr":                                "GR",
	"greenland":                         "GL",
	"gl":                                "GL",
	"grenada":                           "GJ",
	"gd":                                "GJ",
	"guadeloupe":                        "GP",
	"gp":                                "GP",
	"guam":                              "GQ",
	"gu":                                "GQ",
	"guatemala":                         "GT",
	"gt":                                "GT",
	"guernsey":                          "GK",
	"gg":                                "GK",
	"guinea":                            "GV",
	"gn":                                "GV",
	"guinea-bissau":                     "PU",
	"gw":                                "PU",
	"guyana":                            "GY",
	"gy":                                "GY",
	"haiti":                             "HA",
	"ht":                                "HA",
	"heard island and mcdonald islands": "HM",
	"hm":                                "HM",
	"holy see":                          "VT",
	"vatican city":                      "VT",
	"vatican":                           "VT",
	"va":                                "VT",
	"honduras":                          "HO",
	"hn":                                "HO",
	"hong kong":                         "HK",
	"hk":                                "HK",
	"hungary":                           "HU",
	"hu":                                "HU",
	"iceland":                           "IC",
	"is":                                "IC",
	"india":                             "IN",
	"in":                                "IN",
	"indonesia":                         "ID",
	"id":                                "ID",
	"iran (islamic republic of)":        "IR",
	"iran":                              "IR",
	"ir":                                "IR",
	"iraq":                              "IZ",
	"iq":                                "IZ",
	"ireland":                           "EI",
	"ie":                                "EI",
	"isle of man":                       "IM",
	"im":                                "IM",
	"israel":                            "IS",
	"il":                                "IS",
	"italy":                             "IT",
	"it":                                "IT",
	"jamaica":                           "JM",
	"jm":                                "JM",
	"japan":                             "JA",
	"jp":                                "JA",
	"jersey":                            "JE",
	"je":                                "JE",
	"jordan":                            "JO",
	"jo":                                "JO",
	"kazakhstan":                        "KZ",
	"kz":                                "KZ",
	"kenya":                             "KE",
	"ke":                                "KE",
	"kiribati":                          "KR",
	"ki":                                "KR",
	"korea (democratic people's republic of)": "KN",
	"north korea":                      "KN",
	"kp":                               "KN",
	"korea, republic of":               "KS",
	"south korea":                      "KS",
	"kr":                               "KS",
	"kosovo":                           "KV",
	"kuwait":                           "KU",
	"kw":                               "KU",
	"kyrgyzstan":                       "KG",
	"kg":                               "KG",
	"lao people's democratic republic": "LA",
	"laos":                             "LA",
	"la":                               "LA",
	"latvia":                           "LG",
	"lv":                               "LG",
	"lebanon":                          "LE",
	"lb":                               "LE",
	"lesotho":                          "LT",
	"ls":                               "LT",
	"liberia":                          "LI",
	"lr":                               "LI",
	"libya":                            "LY",
	"ly":                               "LY",
	"liechtenstein":                    "LS",
	"li":                               "LS",
	"lithuania":                        "LH",
	"lt":                               "LH",
	"luxembourg":                       "LU",
	"lu":                               "LU",
	"macao":                            "MC",
	"macau":                            "MC",
	"mo":                               "MC",
	"madagascar":                       "MA",
	"mg":                               "MA",
	"malawi":                           "MI",
	"mw":                               "MI",
	"malaysia":                         "MY",
	"my":                               "MY",
	"maldives":                         "MV",
	"mv":                               "MV",
	"mali":                             "ML",
	"ml":                               "ML",
	"malta":                            "MT",
	"mt":                               "MT",
	"marshall islands":                 "RM",
	"mh":                               "RM",
	"martinique":                       "MB",
	"mq":                               "MB",
	"mauritania":                       "MR",
	"mr":                               "MR",
	"mauritius":                        "MP",
	"mu":                               "MP",
	"mayotte":                          "MF",
	"yt":                               "MF",
	"mexico":                           "MX",
	"mx":                               "MX",
	"micronesia (federated states of)": "FM",
	"micronesia":                       "FM",
	"fm":                               "FM",
	"moldova, republic of":             "MD",
	"moldova":                          "MD",
	"md":                               "MD",
	"monaco":                           "MN",
	"mc":                               "MN",
	"mongolia":                         "MG",
	"mn":                               "MG",
	"montenegro":                       "MJ",
	"me":                               "MJ",
	"montserrat":                       "MH",
	"ms":                               "MH",
	"morocco":                          "MO",
	"ma":                               "MO",
	"mozambique":                       "MZ",
	"mz":                               "MZ",
	"myanmar":                          "BM",
	"burma":                            "BM",
	"mm":                               "BM",
	"namibia":                          "WA",
	"na":                               "WA",
	"nauru":                            "NR",
	"nr":                               "NR",
	"nepal":                            "NP",
	"np":                               "NP",
	"netherlands":                      "NL",
	"nl":                               "NL",
	"new caledonia":                    "NC",
	"nc":                               "NC",
	"new zealand":                      "NZ",
	"nz":                               "NZ",
	"nicaragua":                        "NU",
	"ni":                               "NU",
	"niger":                            "NG",
	"ne":                               "NG",
	"nigeria":                          "NI",
	"ng":                               "NI",
	"niue":                             "NE",
	"nu":                               "NE",
	"norfolk island":                   "NF",
	"nf":                               "NF",
	"north macedonia":                  "MK",
	"macedonia":                        "MK",
	"mk":                               "MK",
	"northern mariana islands":         "CQ",
	"mp":                               "CQ",
	"norway":                           "NO",
	"no":                               "NO",
	"oman":                             "MU",
	"om":                               "MU",
	"pakistan":                         "PK",
	"pk":                               "PK",
	"palau":                            "PS",
	"pw":                               "PS",
	"panama":                           "PM",
	"pa":                               "PM",
	"papua new guinea":                 "PP",
	"pg":                               "PP",
	"paraguay":                         "PA",
	"py":                               "PA",
	"peru":                             "PE",
	"pe":                               "PE",
	"philippines":                      "RP",
	"ph":                               "RP",
	"pitcairn":                         "PC",
	"pitcairn islands":                 "PC",
	"pn":                               "PC",
	"poland":                           "PL",
	"pl":                               "PL",
	"portugal":                         "PO",
	"pt":                               "PO",
	"puerto rico":                      "RQ",
	"pr":                               "RQ",
	"qatar":                            "QA",
	"qa":                               "QA",
	"réunion":                          "RE",
	"reunion":                          "RE",
	"re":                               "RE",
	"romania":                          "RO",
	"ro":                               "RO",
	"russian federation":               "RS",
	"russia":                           "RS",
	"ru":                               "RS",
	"rwanda":                           "RW",
	"rw":                               "RW",
	"saint barthélemy":                 "TB",
	"saint barthelemy":                 "TB",
	"bl":                               "TB",
	"saint helena, ascension and tristan da cunha": "SH",
	"saint helena":                     "SH",
	"sh":                               "SH",
	"saint kitts and nevis":            "SC",
	"kn":                               "SC",
	"saint lucia":                      "ST",
	"lc":                               "ST",
	"saint martin (french part)":       "RN",
	"saint martin":                     "RN",
	"mf":                               "RN",
	"saint pierre and miquelon":        "SB",
	"pm":                               "SB",
	"saint vincent and the grenadines": "VC",
	"vc":                               "VC",
	"samoa":                            "WS",
	"ws":                               "WS",
	"san marino":                       "SM",
	"sm":                               "SM",
	"sao tome and principe":            "TP",
	"st":                               "TP",
	"saudi arabia":                     "SA",
	"sa":                               "SA",
	"senegal":                          "SG",
	"sn":                               "SG",
	"serbia":                           "RI",
	"rs":                               "RI",
	"seychelles":                       "SE",
	"sc":                               "SE",
	"sierra leone":                     "SL",
	"sl":                               "SL",
	"singapore":                        "SN",
	"sg":                               "SN",
	"slovakia":                         "LO",
	"sk":                               "LO",
	"slovenia":                         "SI",
	"si":                               "SI",
	"solomon islands":                  "BP",
	"sb":                               "BP",
	"somalia":                          "SO",
	"so":                               "SO",
	"south africa":                     "SF",
	"za":                               "SF",
	"south georgia and the south sandwich islands": "SX",
	"gs":                           "SX",
	"south sudan":                  "OD",
	"ss":                           "OD",
	"spain":                        "SP",
	"es":                           "SP",
	"sri lanka":                    "CE",
	"lk":                           "CE",
	"sudan":                        "SU",
	"sd":                           "SU",
	"suriname":                     "NS",
	"sr":                           "NS",
	"svalbard":                     "SV",
	"sweden":                       "SW",
	"se":                           "SW",
	"switzerland":                  "SZ",
	"ch":                           "SZ",
	"syrian arab republic":         "SY",
	"syria":                        "SY",
	"sy":                           "SY",
	"taiwan, province of china":    "TW",
	"taiwan":                       "TW",
	"tw":                           "TW",
	"tajikistan":                   "TI",
	"tj":                           "TI",
	"tanzania, united republic of": "TZ",
	"tanzania":                     "TZ",
	"tz":                           "TZ",
	"thailand":                     "TH",
	"th":                           "TH",
	"timor-leste":                  "TT",
	"east timor":                   "TT",
	"tl":                           "TT",
	"togo":                         "TO",
	"tg":                           "TO",
	"tokelau":                      "TL",
	"tk":                           "TL",
	"tonga":                        "TN",
	"to":                           "TN",
	"trinidad and tobago":          "TD",
	"tt":                           "TD",
	"tunisia":                      "TS",
	"tn":                           "TS",
	"türkiye":                      "TU",
	"turkiye":                      "TU",
	"turkey":                       "TU",
	"tr":                           "TU",
	"turkmenistan":                 "TX",
	"tm":                           "TX",
	"turks and caicos islands":     "TK",
	"tc":                           "TK",
	"tuvalu":                       "TV",
	"tv":                           "TV",
	"uganda":                       "UG",
	"ug":                           "UG",
	"ukraine":                      "UP",
	"ua":                           "UP",
	"united arab emirates":         "AE",
	"uae":                          "AE",
	"ae":                           "AE",
	"united kingdom of great britain and northern ireland": "UK",
	"united kingdom":                     "UK",
	"great britain":                      "UK",
	"gb":                                 "UK",
	"uk":                                 "UK",
	"united states of america":           "US",
	"united states":                      "US",
	"usa":                                "US",
	"us":                                 "US",
	"uruguay":                            "UY",
	"uy":                                 "UY",
	"uzbekistan":                         "UZ",
	"uz":                                 "UZ",
	"vanuatu":                            "NH",
	"vu":                                 "NH",
	"venezuela (bolivarian republic of)": "VE",
	"venezuela":                          "VE",
	"ve":                                 "VE",
	"viet nam":                           "VM",
	"vietnam":                            "VM",
	"vn":                                 "VM",
	"virgin islands (british)":           "VI",
	"british virgin islands":             "VI",
	"vg":                                 "VI",
	"virgin islands (u.s.)":              "VQ",
	"u.s. virgin islands":                "VQ",
	"vi":                                 "VQ",
	"wallis and futuna":                  "WF",
	"wf":                                 "WF",
	"western sahara":                     "WI",
	"eh":                                 "WI",
	"yemen":                              "YM",
	"ye":                                 "YM",
	"zambia":                             "ZA",
	"zm":                                 "ZA",
	"zimbabwe":                           "ZI",
	"zw":                                 "ZI",
}

// countryFIPS resolves a location to a FIPS 10-4 country code when it
// case-insensitively matches a country name, alias, or ISO 3166-1 alpha-2
// code from the table. Anything else (cities, regions, typos, raw FIPS
// codes) reports false and the caller falls back to quoted-phrase matching.
func countryFIPS(location string) (string, bool) {
	code, ok := fipsCountry[strings.ToLower(strings.TrimSpace(location))]
	return code, ok
}
